### ISSUE TITLE
多处拼音有误

### ISSUE THREAD

**Issue by NekoAria** [Yidadaa/shuangpin#1]
钱钟书的《论快乐》：

```text
德语的沉闷（Langeweile）一字，据字面上直译，就是“长时间”的意思。
```

此处的 “长” 应该是 IH (chang) 而不是 VH (zhang) 。

```text
但是这种“天算”，也有占便宜的地方：
```

此处的 “便” 应该是 PM (pian) 而不是 BM (bian) 。

```text
穆勒曾把“痛苦的苏格拉底”和“快乐的猪”比较。
```

此处的 “勒” 应该是 LE (le) 而不是 LW (lei) 。

```text
要是你精神不痛快，像将离别时的筵席，随它怎样烹调得好
```

此处的 “调” 应该是 TN (tiao) 而不是 DN (diao) 。

```text
在着重体育的西洋
```

此处卡在 “着” ，不管是 VO (zhuo) 还是 VC (zhao) ，都无法通过校验。准确的应该是 VO 。
结果没想到是 VE (zhe) 。😂

---

看了下才发现是用的 `@napi-rs/pinyin` 转的拼音，我想是否可以修改下逻辑，如果是多音字，就直接跳过。
我发现似乎一部分生僻字直接被跳过了，不如连多音字也一并跳过。
最后，感谢做出这个练习工具。

**Comment by Yidadaa** [comment]
多音字的问题确实比较难搞，跳过确实是一个比较好的方法。

**Comment by Yidadaa** [comment]
目前长句模式已支持多音字判定。

<img width="338" alt="image" src="https://user-images.githubusercontent.com/16968934/181810392-9c52eebc-fe75-4ca0-8206-ad388cafb03e.png">

**Comment by silv3rarr0w** [comment]
> 目前长句模式已支持多音字判定。
> 
> <img alt="image" width="338" src="https://user-images.githubusercontent.com/16968934/181810392-9c52eebc-fe75-4ca0-8206-ad388cafb03e.png">

单字模式仍然存在多音字错误问题，特别是韵母模式，如图，在韵母模式OU下，”露“字键入lou的编码无法通过判定，反而需要键入lu的编码，类似问题的多音字在这个模式下还有很多

<img width="1571" height="989" alt="Image" src="https://github.com/user-attachments/assets/b1289c63-a538-4738-8768-ed0f9e6e2e4d" />
