### ISSUE TITLE
多音字无法通过其中一个读音

### ISSUE THREAD

**Issue by V-arc** [Yidadaa/shuangpin#12]
![image](https://user-images.githubusercontent.com/53041402/187430165-8075b223-5d53-4030-b0c7-d22f8d197309.png)

潦倒的潦（liao）不被识别。

**Comment by Yidadaa** [comment]
目前只在长句模式下对多音字做了兼容，单字模式下的本意是为了练习拼音 -> 双拼的肌肉记忆，所以并未兼容多音字，如果支持多音字，在韵母模式下会引起困扰，所以还是建议按照拼音提示来打字。
