### ISSUE TITLE
拼写错误时对应拼写问题

### ISSUE THREAD

**Issue by lomirus** [Yidadaa/shuangpin#13]
以小鹤双拼为例，譬如题目要求汉字为“量（liang）”
此时输入 ll，预览中会自动展示为 "liang"
然而，若题目要求汉字为“打（da）”
此时输入 ll，预览中会展示为 "ll"

不知是否是 bug 抑或 feature。窃以为统一将拼写自动转换为全拼，更能使使用者得到正确的反馈，且逻辑更具一致性。

**Comment by Yidadaa** [comment]
感谢反馈，这是有意为之。

匹配算法会尽可能地匹配候选项，并将已经匹配的拼音展示出来，如果没有匹配到候选拼音，则直接将用户输入反映到屏幕上。

至于哪种方法可以更好地帮助用户形成有效反馈，我觉得是一个仁者见仁智者见智的事情，如果后续有类似的反馈，我会考虑将其作为一个可选配置放到设置页中。

当然，如果你有意增加此功能的话，欢迎直接提交 PR，我会第一时间 Review 你的代码。
