### ISSUE TITLE
如何设置把单韵母的过滤掉，这个不需要练习

### ISSUE THREAD

**Issue by hyaray** [Yidadaa/shuangpin#15]
作为新手，只想纯粹地练习下双拼特色的按键。没找到设置

**Comment by Yidadaa** [comment]
单韵母在不同的双拼方案中，按键方式是不一样的，如果想自定义联系某些按键，可以在：长句模式 -> 鼠标移动到文章标题上  -> 滚动到列表末尾 -> 新建自定义文章，这样你可以自定义联系文本。

**Comment by hyaray** [comment]
以前学五笔，就是先学字根，再练拆字。感觉这种分步走挺好的。
所以我也是想先练按键，再练组合。
可以自定义文本，那也不错了，感谢回复！！
