### ISSUE TITLE
快速按下的两个键，为什么顺序会反了？

### ISSUE THREAD

**Issue by hyaray** [Yidadaa/shuangpin#16]
时间绝对是A在B前的，但是程序显示是B在A前，可能哪里逻辑判断有问题

**Comment by Yidadaa** [comment]
能否提供一下复现的用例？比如按下的拼音，按键的时机，如果能提供录屏更好，顺便提供一下所用浏览器版本，已经操作系统版本，谢谢。

**Comment by hyaray** [comment]
今天试了下，又没怎么遇到了，
这个输入也没什么场景了啊，就是比较快速地按下两键而已，如果没有复现就算了哈。
环境是windows 10，msedge

**Comment by Yidadaa** [comment]
按键顺序是通过队列维护的，应该不太可能出现时序问题，可能是并击过快，导致后面的字符先被按下了。

**Comment by silv3rarr0w** [comment]
> 按键顺序是通过队列维护的，应该不太可能出现时序问题，可能是并击过快，导致后面的字符先被按下了。

这个问题目前还是存在，看了一下原因是这网站判定输入是按照松开按键时算的，但平时打字是按照按下按键算输入算的，所以打字比较快的时候，松开时有时顺序会反过来，就导致了这个情况
