### ISSUE TITLE
感觉在电脑上显示有些小了，空白有些多，请问可不可以开放调整大小呢？

### ISSUE THREAD

**Issue by TXC-ALON** [Yidadaa/shuangpin#18]

**Comment by Yidadaa** [comment]
如果让页面样式自适应缩放的话，样式很容易乱掉，所以就设置成了固定宽高，如果你觉得太小了，可以通过[调整浏览器的缩放设置](https://support.google.com/chrome/answer/96810?hl=zh-Hans&co=GENIE.Platform%3DDesktop)来调整页面缩放。
