### ISSUE TITLE
网页404了，下载代码后，打开index.html也是空白页

### ISSUE THREAD

**Issue by ofen1** [Yidadaa/shuangpin#34]
网页404了，下载代码后，打开index.html也是空白页

**Comment by Ninglo** [comment]
我也遇到了这个问题, index.html 是构建入口而不是产物, 所以需要启动项目. 我 Folk 了仓库把应用部署在了 https://ninglo.github.io/shuangpin/#/key-practice-mode?course=0.
此外,针对当前应用学习曲线不平滑的问题 (默认训练全键位, 作为新人难以一下记忆这么多内容), 开发了更平滑的训练课程, 详细讨论可见 #30.

**Comment by Yidadaa** [comment]
已经启用新域名：https://shuangpin.simplenaive.cn/
