### ISSUE TITLE
白色背景看久了眼睛难受，增加配色或对现有配色进行调整？

### ISSUE THREAD

**Issue by NekoAria** [Yidadaa/shuangpin#4]
虽然可以用 Dark Reader 自己调整。

**Comment by Yidadaa** [comment]
现在已经适配了夜间模式，如果你系统里开了暗色模式，应该会自动启用的。

**Comment by Yidadaa** [comment]
设置选项已经增加强制开启深色模式：

<img width="781" alt="image" src="https://user-images.githubusercontent.com/16968934/181094308-9fcab7d2-7259-4b0d-a9c2-43b573a3fd9f.png">
